# Nombre del workflow (aparecer치 en la GUI)
name: hello-world
# Cu치ndo se ejecuta: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: push
# Listado de jobs
jobs:
  # ID del job. Cada job se ejecuta en una m치quina nueva
  my-job:
    # Tipo de m치quina. Puede ser de Github o un self-hosted runner:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-second-step
        run: echo "Second"
  
  my-third-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16.1' # The Go version to download (if necessary) and use.
      - run: go test -v ./internal/sum/sum_test.go